language: node_js
node_js:
- '6'
deploy:
  api_key:
    secure: mAcjRg3I+aR25wU4c5HwCwXMZXzXhwFVRy0EZttLD2UO181rMBkT4f+tzHmP3UVi9FyroDXZ/qFx97BT+g4zPI5xj+31jcVbEAOkGQOQgG2XgjcJAUWHh1LmltrBy7qwTs5qj+xkXWFKZMngVWsB88oWobsVg27+xk7z68G5fn+/QWxVI1TezdUSKFNIHq5eoaZhvQx161u1lYHLE31pj3FhK+qhV8MnxQ8WM+RsGn3i06APnGUomeEU5ezcEUa1oxRHkSLpHTWewSGtn9eypEN6rcxoPSzakDqreDAGztroS4XLbbbB9jV45rObGll8ZcM+fveFYLkE05yhud4aw3MdQJOIabJ2+TQZS7QUhfCO8MrMGeaR/Ji/S28Bt784DIpgiYdm9r2Nd6O40qWtSelfiUAd2e0NCbaLpsMYPw1HLbgB/0askM6tNbTfqTm7y52/Z4g6uZNHRuNHVpBudcRlfQsqNoOimhbRfSFUwl2ueekNjttCTJtCKu1eqgLF6wvy5KzN3glG6tVoYXQzcaPiO0uaJXJ231bNkcGK5oaAbr4s+S+DIzwO6xJisO2VJ5dz/6aBMU/Q/kLOtkcYFASPcHaFkb+HiIhcBQFXib+BkNGDN5g4i5E8g6D9Kl2P733tgocYHZlv7Xp9IxHGRE4pSgAdlo3n2R2G+bvBpj8=
  email: julian@dotcore.co.il
  provider: npm
  on:
    tags: true
after_script:
- npm run coveralls
services:
- redis-server
